// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using capaEF;

#nullable disable

namespace capaEF.Migrations
{
    [DbContext(typeof(GescomDBContext))]
    [Migration("20251010103014_UpdateMesa2")]
    partial class UpdateMesa2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("capaEntidad.Bebida", b =>
                {
                    b.Property<int>("BebidaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BebidaId"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("BebidaId");

                    b.ToTable("Bebida");
                });

            modelBuilder.Entity("capaEntidad.Caja", b =>
                {
                    b.Property<int>("CajaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CajaId"));

                    b.Property<decimal>("CantFinal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CantInicial")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("EstadoCajaId")
                        .HasColumnType("int");

                    b.HasKey("CajaId");

                    b.HasIndex("EstadoCajaId");

                    b.ToTable("Caja");
                });

            modelBuilder.Entity("capaEntidad.Comanda", b =>
                {
                    b.Property<int>("ComandaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComandaId"));

                    b.Property<int?>("BebidaId")
                        .HasColumnType("int");

                    b.Property<int>("CantComensales")
                        .HasColumnType("int");

                    b.Property<string>("Comentario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ComidaId")
                        .HasColumnType("int");

                    b.Property<int>("EstadoComandaId")
                        .HasColumnType("int");

                    b.Property<int>("MesaId")
                        .HasColumnType("int");

                    b.HasKey("ComandaId");

                    b.HasIndex("BebidaId");

                    b.HasIndex("ComidaId");

                    b.HasIndex("EstadoComandaId");

                    b.HasIndex("MesaId");

                    b.ToTable("Comanda");
                });

            modelBuilder.Entity("capaEntidad.Comida", b =>
                {
                    b.Property<int>("ComidaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComidaId"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ComidaId");

                    b.ToTable("Comida");
                });

            modelBuilder.Entity("capaEntidad.EstadoCaja", b =>
                {
                    b.Property<int>("EstadoCajaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstadoCajaId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EstadoCajaId");

                    b.ToTable("EstadoCaja");
                });

            modelBuilder.Entity("capaEntidad.EstadoComanda", b =>
                {
                    b.Property<int>("EstadoComandaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstadoComandaId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EstadoComandaId");

                    b.ToTable("EstadoComanda");
                });

            modelBuilder.Entity("capaEntidad.EstadoMesa", b =>
                {
                    b.Property<int>("EstadoMesaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstadoMesaId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EstadoMesaId");

                    b.ToTable("EstadoMesa");
                });

            modelBuilder.Entity("capaEntidad.Factura", b =>
                {
                    b.Property<int>("FacturaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FacturaId"));

                    b.Property<int>("ComandaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("MetodoPago")
                        .HasColumnType("int");

                    b.HasKey("FacturaId");

                    b.HasIndex("ComandaId");

                    b.ToTable("Factura");
                });

            modelBuilder.Entity("capaEntidad.Mesa", b =>
                {
                    b.Property<int>("MesaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MesaId"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EstadoMesaId")
                        .HasColumnType("int");

                    b.Property<int>("NumeroMesa")
                        .HasColumnType("int");

                    b.Property<int>("Tamanio")
                        .HasColumnType("int");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MesaId");

                    b.HasIndex("EstadoMesaId");

                    b.ToTable("Mesa");
                });

            modelBuilder.Entity("capaEntidad.Mozo", b =>
                {
                    b.Property<int>("MozoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MozoId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MozoId");

                    b.ToTable("Mozo");
                });

            modelBuilder.Entity("capaEntidad.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("Contrasenia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("capaEntidad.Caja", b =>
                {
                    b.HasOne("capaEntidad.EstadoCaja", "EstadoCaja")
                        .WithMany("Cajas")
                        .HasForeignKey("EstadoCajaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EstadoCaja");
                });

            modelBuilder.Entity("capaEntidad.Comanda", b =>
                {
                    b.HasOne("capaEntidad.Bebida", "Bebida")
                        .WithMany("Comandas")
                        .HasForeignKey("BebidaId");

                    b.HasOne("capaEntidad.Comida", "Comida")
                        .WithMany("Comandas")
                        .HasForeignKey("ComidaId");

                    b.HasOne("capaEntidad.EstadoComanda", "EstadoComanda")
                        .WithMany("Comandas")
                        .HasForeignKey("EstadoComandaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("capaEntidad.Mesa", "Mesa")
                        .WithMany()
                        .HasForeignKey("MesaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bebida");

                    b.Navigation("Comida");

                    b.Navigation("EstadoComanda");

                    b.Navigation("Mesa");
                });

            modelBuilder.Entity("capaEntidad.Factura", b =>
                {
                    b.HasOne("capaEntidad.Comanda", "Comanda")
                        .WithMany()
                        .HasForeignKey("ComandaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comanda");
                });

            modelBuilder.Entity("capaEntidad.Mesa", b =>
                {
                    b.HasOne("capaEntidad.EstadoMesa", null)
                        .WithMany("Mesas")
                        .HasForeignKey("EstadoMesaId");
                });

            modelBuilder.Entity("capaEntidad.Bebida", b =>
                {
                    b.Navigation("Comandas");
                });

            modelBuilder.Entity("capaEntidad.Comida", b =>
                {
                    b.Navigation("Comandas");
                });

            modelBuilder.Entity("capaEntidad.EstadoCaja", b =>
                {
                    b.Navigation("Cajas");
                });

            modelBuilder.Entity("capaEntidad.EstadoComanda", b =>
                {
                    b.Navigation("Comandas");
                });

            modelBuilder.Entity("capaEntidad.EstadoMesa", b =>
                {
                    b.Navigation("Mesas");
                });
#pragma warning restore 612, 618
        }
    }
}
